from .poison import Poison
from .stagger import Stagger
from .defence_debuff import DefenceDebuff
from .magic_resist_debuff import MagicResistDebuff
from .armor import Armor
from .attack_damage_buff import AttackDamageBuff
from .effect import Effect
from .stackable_effect import StackableEffect
from .dodge_buff import DodgeBuff
from .accuracy_debuff import AccuracyDebuff
from .boar_skin import BoarSkin
from .unique import Unique
from .natural_touch import NaturalTouch
